#version: '3.8'
#services:
#  mysql:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: your_password
#      MYSQL_DATABASE: extension_manager
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
#volumes:
#  mysql-data: